name: Deploy to S3 and invalidate CloudFront cache

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::833313251669:role/githubactionsrole
          aws-region: us-east-1

      # 3. Sync files to the first S3 bucket
      - name: Sync files to the first S3 bucket
        run: |
          aws s3 sync . s3://osho-resume --delete

      # 4. Sync files to the second S3 bucket
      - name: Sync files to the second S3 bucket
        run: |
          aws s3 sync . s3://osho-resume-2 --delete

      # 5. Invalidate the first CloudFront cache
      - name: Invalidate the first CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id EMG1I0DLL7VCQ --paths "/*"

      # 6. Invalidate the second CloudFront cache
      - name: Invalidate the second CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E3LQEP5NGVKIEH --paths "/*"
